/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffDashboardRouteImport } from './routes/staff/dashboard'
import { Route as StaffCustomersRouteImport } from './routes/staff/customers'
import { Route as StaffAddCustomerRouteImport } from './routes/staff/add-customer'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as PortalBookingsRouteImport } from './routes/portal/bookings'
import { Route as PortalBookRouteImport } from './routes/portal/book'
import { Route as AdminRequestsRouteImport } from './routes/admin/requests'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as StaffCustomersIdRouteImport } from './routes/staff/customers.$id'
import { Route as AdminCustomersIdRouteImport } from './routes/admin/customers.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCustomersRoute = StaffCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAddCustomerRoute = StaffAddCustomerRouteImport.update({
  id: '/add-customer',
  path: '/add-customer',
  getParentRoute: () => StaffRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBookingsRoute = PortalBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBookRoute = PortalBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PortalRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const StaffCustomersIdRoute = StaffCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffCustomersRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/portal/book': typeof PortalBookRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/staff/add-customer': typeof StaffAddCustomerRoute
  '/staff/customers': typeof StaffCustomersRouteWithChildren
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/staff/customers/$id': typeof StaffCustomersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/portal/book': typeof PortalBookRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/staff/add-customer': typeof StaffAddCustomerRoute
  '/staff/customers': typeof StaffCustomersRouteWithChildren
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/staff/customers/$id': typeof StaffCustomersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/portal/book': typeof PortalBookRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/staff/add-customer': typeof StaffAddCustomerRoute
  '/staff/customers': typeof StaffCustomersRouteWithChildren
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/login': typeof StaffLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/staff/customers/$id': typeof StaffCustomersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/login'
    | '/portal'
    | '/privacy'
    | '/refund'
    | '/services'
    | '/signup'
    | '/staff'
    | '/terms'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/requests'
    | '/portal/book'
    | '/portal/bookings'
    | '/portal/dashboard'
    | '/staff/add-customer'
    | '/staff/customers'
    | '/staff/dashboard'
    | '/staff/login'
    | '/admin/'
    | '/admin/customers/$id'
    | '/staff/customers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/login'
    | '/portal'
    | '/privacy'
    | '/refund'
    | '/services'
    | '/signup'
    | '/staff'
    | '/terms'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/requests'
    | '/portal/book'
    | '/portal/bookings'
    | '/portal/dashboard'
    | '/staff/add-customer'
    | '/staff/customers'
    | '/staff/dashboard'
    | '/staff/login'
    | '/admin'
    | '/admin/customers/$id'
    | '/staff/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/login'
    | '/portal'
    | '/privacy'
    | '/refund'
    | '/services'
    | '/signup'
    | '/staff'
    | '/terms'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/requests'
    | '/portal/book'
    | '/portal/bookings'
    | '/portal/dashboard'
    | '/staff/add-customer'
    | '/staff/customers'
    | '/staff/dashboard'
    | '/staff/login'
    | '/admin/'
    | '/admin/customers/$id'
    | '/staff/customers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  StaffRoute: typeof StaffRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/customers': {
      id: '/staff/customers'
      path: '/customers'
      fullPath: '/staff/customers'
      preLoaderRoute: typeof StaffCustomersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/add-customer': {
      id: '/staff/add-customer'
      path: '/add-customer'
      fullPath: '/staff/add-customer'
      preLoaderRoute: typeof StaffAddCustomerRouteImport
      parentRoute: typeof StaffRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/bookings': {
      id: '/portal/bookings'
      path: '/bookings'
      fullPath: '/portal/bookings'
      preLoaderRoute: typeof PortalBookingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/book': {
      id: '/portal/book'
      path: '/book'
      fullPath: '/portal/book'
      preLoaderRoute: typeof PortalBookRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/customers/$id': {
      id: '/staff/customers/$id'
      path: '/$id'
      fullPath: '/staff/customers/$id'
      preLoaderRoute: typeof StaffCustomersIdRouteImport
      parentRoute: typeof StaffCustomersRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalBookRoute: typeof PortalBookRoute
  PortalBookingsRoute: typeof PortalBookingsRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBookRoute: PortalBookRoute,
  PortalBookingsRoute: PortalBookingsRoute,
  PortalDashboardRoute: PortalDashboardRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface StaffCustomersRouteChildren {
  StaffCustomersIdRoute: typeof StaffCustomersIdRoute
}

const StaffCustomersRouteChildren: StaffCustomersRouteChildren = {
  StaffCustomersIdRoute: StaffCustomersIdRoute,
}

const StaffCustomersRouteWithChildren = StaffCustomersRoute._addFileChildren(
  StaffCustomersRouteChildren,
)

interface StaffRouteChildren {
  StaffAddCustomerRoute: typeof StaffAddCustomerRoute
  StaffCustomersRoute: typeof StaffCustomersRouteWithChildren
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffLoginRoute: typeof StaffLoginRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAddCustomerRoute: StaffAddCustomerRoute,
  StaffCustomersRoute: StaffCustomersRouteWithChildren,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffLoginRoute: StaffLoginRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  StaffRoute: StaffRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
